[package]
name = "worker"
version = "0.1.0"
authors = ["abel <raojianli66@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonrpc-derive = "15.0.0"
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "15.0.0"